# Generated by Django 4.2.1 on 2023-05-25 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='new_category',
            new_name='newCategory',
        ),
    ]
