# Generated by Django 4.2.1 on 2023-05-25 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_new_category_category_newcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='newCategory',
            new_name='name',
        ),
    ]
