# Generated by Django 4.2.1 on 2023-05-27 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_category_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subscribers',
        ),
    ]
